# Generated by Django 4.2.5 on 2023-09-26 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='menu_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table', to='core.restaurant'),
        ),
    ]
