# Generated by Django 4.2.5 on 2023-09-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_table_menu_url_table_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='menu_url',
        ),
        migrations.RemoveField(
            model_name='table',
            name='restaurant',
        ),
    ]
