# Generated by Django 5.0.6 on 2024-05-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
