# Generated by Django 5.0.6 on 2024-07-02 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0003_restaurant_business_hours_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_charge', models.DecimalField(decimal_places=2, default=0.51, max_digits=10)),
                ('currency', models.CharField(default='LRD', max_length=3)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu_dashboard.orders')),
            ],
        ),
    ]
