# Generated by Django 5.0.6 on 2024-07-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0007_usercode_topuprequest_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
