# Generated by Django 5.0.6 on 2024-06-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0007_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Credit Card', 'Credit Card')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='table_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
