# Generated by Django 5.0.6 on 2024-06-01 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0008_orders_payment_method_orders_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='table_number',
        ),
    ]
