# Generated by Django 5.0.6 on 2024-06-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0011_rename_amount_orders_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='total_amount',
            new_name='amount',
        ),
    ]
