# Generated by Django 5.0.6 on 2024-09-21 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0011_customer_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu_dashboard.restaurant'),
        ),
    ]
